#!/bin/sh

docker rm -f foxhole >/dev/null 2>&1

docker exec -it $(docker run --pull always --name=foxhole -v "/foxhole:/foxhole" -v "/etc/letsencrypt:/etc/letsencrypt" -qdp 80:80 -p 443:443 ghcr.io/smikhalevski/foxhole:master) configure
